### ISSUE TITLE
Why do integer values for x and y always return 0 for noise.perlin?

### ISSUE THREAD

**Issue by TheBunyip** [josephg/noisejs#13]
Is that right?

**Comment by Qix-** [comment]
Facing the same thing; this definitely isn't right.

**Comment by josephg** [comment]
I just had a good look through the code and I think it is correct.

Other implementations also have the same property: https://forum.libcinder.org/topic/perlin-returns-zero-for-all-integer-arguments

Or [here](http://flafla2.github.io/2014/08/09/perlinnoise.html):
> Flafla2 Mod  g c • 4 months ago
> You are only using integral input coordinates. Because of the "unit square" nature of perlin noise all integral coordinates are 0.5 (eg perlin(1.0,2.0,3.0) == 0.5). Figure 4 illustrates this; at all of the integral coordinates (at the corners) the value is 0.5.

Its not really a big deal - usually you will either sum multiple iterations of perlin noise at different frequencies & amplitudes or mostly use values in between.

You can visually see the same thing happening here at the grid lines:

![](http://flafla2.github.io/img/2014-08-09-perlinnoise/logic04.png)

**Comment by TheBunyip** [comment]
Good explanation Joseph.  That has helped to solidify my understanding of how Perlin works, thanks. :)
