### ISSUE TITLE
License confusin, the files says ICS but the file inside says public domain? 

### ISSUE THREAD

**Issue by treeform** [josephg/noisejs#21]
It would be nice if the library present a unified license picture?

**Comment by josephg** [comment]
The code is a port of some code that was placed in the public domain. Public domain isn't a real legal thing in most jurisdictions though.

I don't care. What do you want me to do?

**Comment by treeform** [comment]
I think it would be nice if one of two things would happen:
* removal of the comments talking about license from the file so that the main LICENSE file speaks for the code base. https://gist.github.com/treeform/f202f8ed80cd7c2c96da089ee0af5196
* change to the the comments saying its under the ISC License rather then public domain + attribution.

Both are pretty simple.

**Comment by josephg** [comment]
👍 fixed
