### ISSUE TITLE
FYI: 'Pretty' Demo Is a Dead Link

### ISSUE THREAD

**Issue by sam1rm** [josephg/noisejs#23]
![screen shot 2017-12-05 at 5 54 43 pm](https://user-images.githubusercontent.com/1094573/33640429-6a8b6600-d9e5-11e7-9c78-59ab6976359f.png)

**Comment by sam1rm** [comment]
Guessing you have to renew your certificate. Excited to see the demo!

**Comment by jebarjonet** [comment]
On my side there is no problem and no warning right now 🙂 

@sam1rm You could still click `Advanced` and chose to check out the demo anyway (your browser is just warning you, not preventing navigation)

**Comment by josephg** [comment]
Oh yeah, nginx on my linode sometimes isn't noticing rotated letsencrypt certs. Not sure whats going on; but now and then I need to kick it to fix SSL errors. Sorry about that
