### ISSUE TITLE
simplex3 value range fix

### ISSUE THREAD

**Issue by 0xAnime** [josephg/noisejs#6]
```
var t1 = 0.5 - x1*x1-y1*y1-z1*z1;
var t2 = 0.5 - x2*x2-y2*y2-z2*z2;
var t3 = 0.5 - x3*x3-y3*y3-z3*z3;
```

should be

```
var t1 = 0.6 - x1*x1-y1*y1-z1*z1;
var t2 = 0.6 - x2*x2-y2*y2-z2*z2;
var t3 = 0.6 - x3*x3-y3*y3-z3*z3;
```

source: http://staffwww.itn.liu.se/~stegu/simplexnoise/simplexnoise.pdf

**Comment by jlmakes** [comment]
I believe this was a regression.

The original PDF predates the [improvements made in 2012](http://staffwww.itn.liu.se/~stegu/simplexnoise/SimplexNoise.java) (which is what appears to be the source of this port), and has since been updated to indicate that `0.5` is indeed the correct value.
